package com.zhijia.zcms.model.tes;

import static javax.persistence.GenerationType.IDENTITY;

// Generated 2016-10-21 16:55:23 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "tes_department")
public class Department{
	private Integer id;
	private String name;
	private String floor;
/*	private Set<Employee> employees = new HashSet<Employee>();
*/
	public Department() {
	}

	public Department(String name, String floor, Set employees) {
		this.name = name;
		this.floor = floor;
		//this.employees = employees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "floor", length = 100)
	public String getFloor() {
		return this.floor;
	}

	public void setFloor(String floor) {
		this.floor = floor;
	}
/*
	@OneToMany(targetEntity=Employee.class)
	@JoinColumn(name="department_id",referencedColumnName="department_id")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}*/

}
